### ISSUE TITLE
"Cannot read property 'sha' of undefined" when nothing to merge

### ISSUE THREAD

**Issue by PaulMougel** [tukasz/direct-merge-action#18]
Hi, and thanks for this GitHub Action which is great!

We just started using it in our repository. We use it to merge fixes from stable branches into our development branches automatically.

We got this error which happened where there was nothing to merge between two branches:
```
Error: An unexpected error occurred: Cannot read property 'sha' of undefined
```

Is there a way to handle this edge case?

**Comment by tukasz** [comment]
Hi Paul,

Let me check this and I'll get back to you.

**Comment by tukasz** [comment]
Yes, I'll be updating the action to better handle non-success cases.

New version should be available tomorrow.

**Comment by PaulMougel** [comment]
Wow, awesome! I'll be glad to test and give feedback.

**Comment by tukasz** [comment]
A [2.0](https://github.com/tukasz/direct-merge-action/releases/tag/v2.0) version of the action has been published.

Hope that it will resolve the problems that had emerged so far.

And of course, any feedback is very welcome.

**Comment by PaulMougel** [comment]
Very much appreciated, thanks a lot.

We'll upgrade our dependencies and let you know.

**Comment by PaulMougel** [comment]
Confirming that the new version works well 👍  

Thanks again!

**Comment by tukasz** [comment]
You're welcome and thank you for the update.
